#!/bin/sh

#for managing timecards at work

#In the morning run:
# ./punch in
#When you leave run:
# ./punch out

#This will create a file called time 
#with arrival/departure times every day

if [ "$1" = "in" ] 
then
	echo "in :" >> time
	date >> time

elif [ "$1" = "out" ] 
then
	echo "out:" >> time
	date >> time
        echo "\n" >> time

else 
	echo "in or out?"
        exit 1

cat time
exit 1

fi
